# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-16 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, max_length=32, verbose_name='用户名'),
        ),
    ]
